dev:
  clockify:
    apiKey: $CLOCKIFY_API_KEY
    workspaceId: $CLOCKIFY_WORKSPACE_ID
    userId: $CLOCKIFY_USER_ID
  wave:
    accessToken: $WAVE_ACCESS_TOKEN
    recipientId: $WAVE_RECIPIENT_ID
    businessId: $WAVE_BUSINESS_ID
    customerId: $WAVE_CUSTOMER_ID
    productId: $WAVE_PRODUCT_ID
  hourlyRate: $HOURLY_RATE
production:
  clockify:
    apiKey: $CLOCKIFY_API_KEY
    workspaceId: $CLOCKIFY_WORKSPACE_ID
    userId: $CLOCKIFY_USER_ID
  wave:
    accessToken: $WAVE_ACCESS_TOKEN
    recipientId: $WAVE_RECIPIENT_ID
    businessId: $WAVE_BUSINESS_ID
    customerId: $WAVE_CUSTOMER_ID
    productId: $WAVE_PRODUCT_ID
  hourlyRate: $HOURLY_RATE